"""Second script

Revision ID: 0e7030c5149c
Revises: ed6955b9a26c
Create Date: 2023-05-28 00:11:33.298312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7030c5149c'
down_revision = 'ed6955b9a26c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
