"""Second scripts

Revision ID: 40fe15f29af1
Revises: 0e7030c5149c
Create Date: 2023-05-28 00:15:18.666888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40fe15f29af1'
down_revision = '0e7030c5149c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
