"""Create tables

Revision ID: 7108b36a37c9
Revises: 19e867ff856b
Create Date: 2023-05-28 00:22:35.416691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7108b36a37c9'
down_revision = '19e867ff856b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
