"""Create Tabless

Revision ID: bff9b1c6fc05
Revises: 3f3289c5a28c
Create Date: 2023-06-02 13:39:36.616839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff9b1c6fc05'
down_revision = '3f3289c5a28c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
