"""Commit database

Revision ID: cd405d5e40e8
Revises: 2bce8c634073
Create Date: 2023-05-28 07:21:07.770999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd405d5e40e8'
down_revision = '2bce8c634073'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
